name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to deploy (e.g., v1.2.3)'
        required: true
        type: string

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version || github.ref }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for staging
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging..."
          echo "TODO: Add your staging deployment command here"
          echo "Examples:"
          echo "  - Vercel: vercel --prod --token=\$VERCEL_TOKEN"
          echo "  - Netlify: netlify deploy --prod --auth=\$NETLIFY_TOKEN"
          echo "  - AWS S3: aws s3 sync dist/ s3://your-bucket/"
          echo "  - Firebase: firebase deploy --only hosting:staging"

      - name: Staging deployment summary
        run: |
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          echo "✅ Deployed $VERSION to staging"

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://example.com

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version || github.ref }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production..."
          echo "TODO: Add your production deployment command here"
          echo "Examples:"
          echo "  - Vercel: vercel --prod --token=\$VERCEL_TOKEN"
          echo "  - Netlify: netlify deploy --prod --auth=\$NETLIFY_TOKEN"
          echo "  - AWS S3: aws s3 sync dist/ s3://your-bucket/"
          echo "  - Firebase: firebase deploy --only hosting:production"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          release_name: Release ${{ github.event.inputs.version || github.ref_name }}
          body: |
            ## Changes
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)
            
            ## Deployment
            - ✅ Staging: https://staging.example.com
            - ✅ Production: https://example.com
          draft: false
          prerelease: false

      - name: Production deployment summary
        run: |
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          echo "✅ Deployed $VERSION to production"
          echo "🎉 Release complete!"
